### ISSUE TITLE
Upload: Automatic image scaling

### ISSUE THREAD

**Issue by mukrop** [repli2dev/scienceslam#1]
Have a possibility to automatically scale photos when uploading.

**Comment by repli2dev** [comment]
The PHP utility for processing images is not something you would like to use... Why is `mogrify` not sufficient?

**Comment by mukrop** [comment]
Didn't know about mogrify (I use GIMP's batch processor localy). As written elsewhere, the point is to allow gallery creation for more people, to make it more convenient and less prone to do something wrong.

**Comment by repli2dev** [comment]
Will be solves as #19
