### ISSUE TITLE
Cannot upload photos to /images/organizers

### ISSUE THREAD

**Issue by mukrop** [repli2dev/scienceslam#10]
Uploading a photo through administrator interface produces error 500.
Any ideas why?

**Comment by repli2dev** [comment]
Plenty (too big file, too slow upload to exceed PHP timelimit, permissions problems, invalid names,...)

Cannot access server now so without appropriate log file from logs dir I cannot do anything more.

**Comment by mukrop** [comment]
Ok, it's not that pressing. We can have a look at it together someday.

**Comment by repli2dev** [comment]
Reproducable bug, though it will need logs from `log` dir.

**Comment by mukrop** [comment]
Can you specify the timestamp you are interested in? (I'll fetch you the logs.)

**Comment by repli2dev** [comment]
Around 22.6. 2017 9:43

**Comment by mukrop** [comment]
Email sent.

**Comment by repli2dev** [comment]
This is filesystem permission bug. Attemption to provide mechanism to fix this issue will be in the v2017.
