### ISSUE TITLE
Implement HTTPS

### ISSUE THREAD

**Issue by repli2dev** [repli2dev/scienceslam#14]
After testing that the page works under https, it would be nice to switch to HTTPS as it is field standard, also now prefered by Google etc.

Estimated time: **1 hour**

**Comment by mukrop** [comment]
Please add CSR as PEM and I'll have a TERENA/DigiCert MU certificate issued. What validity do we want (1-3 years)?

**Comment by repli2dev** [comment]
Resolved together with #15 (deployment of first increment).
