### ISSUE TITLE
Add basic developer documentation

### ISSUE THREAD

**Issue by repli2dev** [repli2dev/scienceslam#17]
Developer:

- Application requirements
- Application (source) structure
- Deployment process and structure (servers + plan of backups)
- Typical operations (changes of logos, footer, header, styling...)

Estimated time: **3 hours**

**Comment by repli2dev** [comment]
What should be the language of this documentation?

**Comment by mukrop** [comment]
English or Czech, does not really matter to me. If there are comment in the code in one of the languages, I slightly prefer to be consistent.

**Comment by repli2dev** [comment]
Please check whether it fulfills your expectations.

Spent time: **2.5 hours**
