### ISSUE TITLE
Automatic photogallery creation

### ISSUE THREAD

**Issue by mukrop** [repli2dev/scienceslam#2]
Upload photos -> generate thumbs, scale originals, create html page

**Comment by repli2dev** [comment]
Does it need to be HTML page? Would be gallery with just uploading images (and/or thumbs) be better solution?

**Comment by mukrop** [comment]
I probably don't understand your idea. The point is automation -- so that the gallery can be created by a non-IT guy (e.g. Petr).

Currently, I am resizing the thumbs locally, editing the previous year's html (generating a new one) and uploading the html, images and thumbs separately.

**Comment by repli2dev** [comment]
Will be solves as #19.
