### ISSUE TITLE
Set up Facebook Pixel

### ISSUE THREAD

**Issue by mukrop** [repli2dev/scienceslam#23]
https://www.facebook.com/business/a/facebook-pixel
https://www.facebook.com/business/help/952192354843755

ID available in my inbox

**Comment by repli2dev** [comment]
Estimate: **20-30 minutes** (basic tracking, event tracking can take some time extra).

**Comment by repli2dev** [comment]
Commited to master, when ready just provide `parameters.facebook.analytics` or `parameters.google.analytics`value which activates the appropriate JS snippet.

(Google analytics implemented as it was easy and could be handy in future.

Used time: **30 minutes**
