### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by mukrop** [repli2dev/scienceslam#26]
* Oko vs. construction sa mi zdaju neintuitivne -- bral som to ako indikator, nie ako tlacitko, ktore oznacuje, co sa stane, ked ho stacim. Mozem poprosit vymenit ich?
* Sipky vedla vahy su teraz neintuitivne, lebo sipka dole zvysuje cislo a sipha hore ho znizuje. Prosim vymenit obrazok sipiek (tj. vlavo bude sipka dole, ktora bude mat efekt aktualnej sipky hore -- znizi vahu a posunie blok viac vlavo).
* Viem nejako v dlazdiciach metagalerie nahodit popis na bloku ku galerii (tj. nie modry nadpis, ale ten cierny text pod tym)?
* Ake je poradie blokov v metagalerii? Viem ho nejako upravit? (Chcel by som.) Vzhladom aj na tie popisy vaham, ci pre mna nie je strategickejsie su vyrobit standardnu blokovu stranku s odkazmi, kde to bduem moct prehadzovat a editovat podla chcenia. Nedao by sa to nejako nakombinovat? Akoze pri vytvoreni galerie by sa vytvoril blok v meta (resp. by bolo explicitne zatrzitko "teraz vytvorit blok do meta", ktore by ho vytvorilo nezavisle na tom, ci tam uz je a ja by som si su meta editoval ako standardnu blokovu stranku...).
    * Aha, uz vidim, ze v uprave stranky mozem  nastavit vahu. Znacne neohrabane, ale funguje.
* Dalo by sa vsetkym linkom v Texy vlozit class="link"?
* Gallerie ked dostanu do cesty neexistujuci adresar, tak pri nacitani stranky server hodi 500.

**Comment by repli2dev** [comment]
> Oko vs. construction sa mi zdaju neintuitivne -- bral som to ako indikator, nie ako tlacitko, ktore oznacuje, co sa stane, ked ho stacim. Mozem poprosit vymenit ich?

Ok, změnil jsem.
> Sipky vedla vahy su teraz neintuitivne, lebo sipka dole zvysuje cislo a sipha hore ho znizuje. Prosim vymenit obrazok sipiek (tj. vlavo bude sipka dole, ktora bude mat efekt aktualnej sipky hore -- znizi vahu a posunie blok viac vlavo).

Ok, změnil jsem to, teď to přijde neintuitivní mě, ale uvidíme.
> Viem nejako v dlazdiciach metagalerie nahodit popis na bloku ku galerii (tj. nie modry nadpis, ale ten cierny text pod tym)?

Přidal jsem tam tu možnost, při nasazení bude potřeba spustit `006_GALLERY_META2.sql` (přibylo to jako pole v nastavení stránky.
> Ake je poradie blokov v metagalerii? Viem ho nejako upravit? (Chcel by som.) Vzhladom aj na tie popisy vaham, ci pre mna nie je strategickejsie su vyrobit standardnu blokovu stranku s odkazmi, kde to bduem moct prehadzovat a editovat podla chcenia. Nedao by sa to nejako nakombinovat? Akoze pri vytvoreni galerie by sa vytvoril blok v meta (resp. by bolo explicitne zatrzitko "teraz vytvorit blok do meta", ktore by ho vytvorilo nezavisle na tom, ci tam uz je a ja by som si su meta editoval ako standardnu blokovu stranku...).
> Aha, uz vidim, ze v uprave stranky mozem nastavit vahu. Znacne neohrabane, ale funguje.

Ano, je to dle váhy... přidal jsem na metagalerii stejné tlačítka jako u bloků, akorát tady to spravuje stránky a posouvá váhy stránek pro galerii.
> Dalo by sa vsetkym linkom v Texy vlozit class="link"?

Ano, zařídil jsem to u všech odkazů, které projdou přes Texy (netýká se HTML).
> Gallerie ked dostanu do cesty neexistujuci adresar, tak pri nacitani stranky server hodi 500.

Opraveno.

**Comment by mukrop** [comment]
Nastenka zatial neexistuje a ked do nej pridam prvy text, tak sa neulozi. Skusil som prihlasit/odhlasit, force-refresh aj dropnout cache.

**Comment by repli2dev** [comment]
Hmm, zkus nastavit složce `/data` práva pro `www-data` (asi 770 pokud je jako skupina).

**Comment by mukrop** [comment]
Zmena prav to vyriesila. Skupina je muni a neviem ju zmenit. (Fakt to ne-root uzivatel nemoze?) Nastavil som ACL a uz to ide. Stoji za to to nastavene ACL niekde spominat v dokumentacii?

**Comment by repli2dev** [comment]
Přidal jsem to tam.
