### ISSUE TITLE
Notes document in administration

### ISSUE THREAD

**Issue by mukrop** [repli2dev/scienceslam#27]
Hm, mohol by som mat na hlavnej stranke administracie textove pole, do ktoreho mozu vsetci editori pisat poznamky a vidiet ich?
Use case: Ja si tam teraz poznacim (pre mna aj dalsich), aku mam mennu konveciu, v akom rozliseni uploadujem fotky a pod. Wiki-style, kazdy moze editovat. Staci cisty text (ale Texy tiez neurazi).

Realisticke? Mohlo by to byt tak cca pol hodina, nie?

**Comment by repli2dev** [comment]
Byla to ta cca půl hodina, takže jsem to udělal.
