### ISSUE TITLE
Fix gallery generation

### ISSUE THREAD

**Issue by mukrop** [repli2dev/scienceslam#28]
@repli2dev, what is your time estimate for that?

**Comment by repli2dev** [comment]
Probably the cache directory will have to be public and thumbnails generated manually (after click).

Estimated time: **1-3 hours**

**Comment by mukrop** [comment]
Any update here? I'd like to close the web redevelopment.

**Comment by repli2dev** [comment]
Work in progress, however not to be finished until the end of the next week (I'd like to close this iteration too asap.)

**Comment by repli2dev** [comment]
Should be finished...

New solution doesn't create thumbnails on the fly, nor pass these thumbnails through PHP... All images from page referenced `gallery_path` and `gallery_meta_title` are pregenerated on adding/editing page or when explicit regeneration is requested. All cached images goes into `/cached_images` which is public to be handled by Apache directly.

This solution has some drawbacks, namely the cache dir will grow as there there is no removal of images (as this is garbage collection problem). Also making changes through file manager will need manual intervention (click on regeneration link) -- but for sake of clarity I have added column "Gallery" into Pages list and tag (gallery) to file manager when the directory is referenced as gallery.

Moreover when the original or cache image doesn't exists there is no broken image (it's completely ignored).

Spent time: approximately 3.5 hours.

**Comment by mukrop** [comment]
Should I expect deployment complications, or should it be painless? Any interaction needed with the galleries created in the old system?

**Comment by repli2dev** [comment]
Two manual interventions expected: remove old caching dir from temp dir; chmod 777 the `cached_images` dir. Apart from that it should be without complications. (And then regenerate the galleries of course ;-))

**Comment by mukrop** [comment]
Turned out a bit problematic, see email.
