### ISSUE TITLE
Allow for bulk file upload (more than 25 files at a time?)

### ISSUE THREAD

**Issue by mukrop** [repli2dev/scienceslam#3]

**Comment by repli2dev** [comment]
Tough for implementing as this is tightly connected to PHP memory and time limits which limits how many files you can upload.

Way to bypass the issue is to implement some uploader (which is bunch of work) that uploads one-by-one (such as Dropzone).

ETA: 16-24h

**Comment by mukrop** [comment]
In that case the cost will probably outweigh the advantages.

**Comment by mukrop** [comment]
Not cost-effective and thus not requested anymore.
