### ISSUE TITLE
Nicer photogalleries

### ISSUE THREAD

**Issue by mukrop** [repli2dev/scienceslam#4]
* Use Fancybox for viewing original images (http://fancyapps.com/fancybox/).
* Optional: Use Masonry for photo grid (http://masonry.desandro.com/).

**Comment by repli2dev** [comment]
Point accepted, however the precise choise should be considered thoroughly as vaste number of such solutions has some drawback such as: not working on Android/iOS... not responsive etc.

**Comment by mukrop** [comment]
Sure, this was just an example (I used this after a small market study several years back).

**Comment by repli2dev** [comment]
Will be solves as #19.
