### ISSUE TITLE
Dedicated photogallery section

### ISSUE THREAD

**Issue by mukrop** [repli2dev/scienceslam#5]
Consider creating a dedicated photogallery section on the title page. This will be useful if we start uploading more photos (Prague slam, Science tour, ...)

**Comment by repli2dev** [comment]
Needs more precise specification.

**Comment by mukrop** [comment]
More of a note to self about reorganizing the menu in the page. If done, I can do it myself in about an hour.

**Comment by repli2dev** [comment]
@mukrop is this the desired meta-gallery page as specified in #19?

**Comment by mukrop** [comment]
Yes, that is the superset of this issue.
