### ISSUE TITLE
Admin block display improvements

### ISSUE THREAD

**Issue by mukrop** [repli2dev/scienceslam#6]
In administrative view (when logged in):
* Add visual indicator on hidden blocks.
* Add toggle for hide/show block (ideally directly clicking on the indicator).
* Add an easier way to rearrange blocks (since getting drag-and-drop is probably an overkill, add 2 overlay buttons for right/left movement that change the weight).
* Add overlay button to edit/delete the block.
* Reformat "Add block" button as an extra block at the end with a big + sign.

Adding all of above cause the block list to be redundant -- and thus can be hidden completely.

**Comment by repli2dev** [comment]
- Drag and drop is an overkill, buttons are not.

Estimated time: **4 hours**

**Comment by repli2dev** [comment]
Implemented, though it was tough as browsers cannot handle link element in another link element. Therefore major restructuralization of blocks layout (div > a) was needed.

Notes:
- Visual indication of visibility is done via color of hiding/showing button in the bar (borders and opacity seemed as bad idea).
- Weights are incremented by one as other solution to swap blocks is not an easily implementable. Its a bit quirky as when weight is the same, order is done by ID, therefore swap didn't happen.
- Changes in visibility and weights happen via ajax request, reloading is not needed ;-)

Spent time: **3 hours** (updated after recent fixies of AJAX redrawing)
