### ISSUE TITLE
Add file replacement confirmation

### ISSUE THREAD

**Issue by mukrop** [repli2dev/scienceslam#8]
When uploading file, warn (and ask for confirmation), if file with the same name already exists.

**Comment by repli2dev** [comment]
Kind of tricky, as dividing one request to two request with handing over what files are uploaded and to be confirmed complicates stuff.

ETA: 8-16 h.

**Comment by mukrop** [comment]
Ok, maybe not worth the effort.

**Comment by repli2dev** [comment]
What about confirming in advance (as in IS) via checkbox? That would be like 0.5 hour.

**Comment by mukrop** [comment]
Checkbox is definitely a more cost-effective option, let's go for that one. Counting **~1 hour**.

**Comment by repli2dev** [comment]
Done, also I have implemented various checks and added more messages when deletion/upload fails as well as tool for fixing permissions to 777/666 in upload dirs (will see if that works).

Used time: **1 hour**
