### ISSUE TITLE
Block image selection

### ISSUE THREAD

**Issue by mukrop** [repli2dev/scienceslam#9]
Make block background image selection more practical. The more images there are, the more impractical is to find the one you're looking for...

**Comment by repli2dev** [comment]
Potential solutions:
 - select embeded style background.
 - library for embeding images in select

ETA: 1-4 h

**Comment by repli2dev** [comment]
Thinking about the autocomplete, this doesn't seem to be usable... the only proper solution is file manager :/

**Comment by repli2dev** [comment]
Implemented via the same preview button as in file manager... There will be link next to the select, clicking on it will open iframe with the selected image inside. That should easy the process though it is not a file manager... its up to you if this is acceptable implementation.

Spent time: **30 minutes**
